name: update-tensorflow

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  generate-examples-job:
    runs-on: ubuntu-18.04
    env:
      GH_SERVICE_ACCOUNT_NAME: "tflite-bot"
      GH_SERVICE_ACCOUNT_EMAIL: "tflite-bot@antmicro.com"
      GH_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Clone target repository
        uses: actions/checkout@v2
        with:
          repository: "antmicro/tensorflow-zephyr-vexriscv-examples"
          path: "target_repo"
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
          submodules: recursive

      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL

      - name: GH CLI auth
        run: echo $GH_SERVICE_ACCOUNT_TOKEN | gh auth login --with-token

      - name: Bump tflite-micro, commit and push
        run: |
          export NEW_BRANCH=bot-$(date +%F_%H-%M)
          cd target_repo
          git checkout -b $NEW_BRANCH
          pushd tflite-micro
          git checkout main
          git pull
          export TENSORFLOW_MASTER=$(git rev-parse --short HEAD)
          popd
          git add .

          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update Tensorflow Lite Micro to $TENSORFLOW_MASTER";
            git push -u https://$GH_SERVICE_ACCOUNT_NAME:$GH_SERVICE_ACCOUNT_TOKEN@github.com/antmicro/tensorflow-zephyr-vexriscv-examples.git $NEW_BRANCH
            gh pr create --fill --head $NEW_BRANCH
            gh pr review --approve
            gh pr merge --auto --delete-branch
          else
            echo "no changes";
          fi
