name: tensorflow-zephyr-vexriscv-examples-bump-zephyr

on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:
  push:

jobs:
  generate-examples-job:
    runs-on: ubuntu-18.04
    env:
      GH_SERVICE_ACCOUNT_NAME: "tflite-bot"
      GH_SERVICE_ACCOUNT_EMAIL: "tflite-bot@antmicro.com"
      GH_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Clone target repository
        uses: actions/checkout@v2
        with:
          repository: "antmicro/tensorflow-zephyr-vexriscv-examples"
          path: "target_repo"
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
          submodules: recursive

      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL

      - name: GH CLI auth
        run: echo $GH_SERVICE_ACCOUNT_TOKEN | gh auth login --with-token

      - name: Bump Zephyr, commit and push
        run: |
          cd target_repo
          git fetch
          git checkout bump-zephyr
          export NEW_BRANCH=bot-$(date +%F_%H-%M)-bump-zephyr
          export ZEPHYR_SHA=$(git ls-remote https://github.com/zephyrproject-rtos/zephyr.git main | cut -c1-7)
          echo $ZEPHYR_SHA > zephyr_new.sha

          if ! cmp -s "zephyr.sha" "zephyr_new.sha" ; then
            mv zephyr_new.sha zephyr.sha
            git checkout -b $NEW_BRANCH
            git add .
            git commit -m "Update Zephyr SHA to $ZEPHYR_SHA";
            git push -u https://$GH_SERVICE_ACCOUNT_NAME:$GH_SERVICE_ACCOUNT_TOKEN@github.com/antmicro/tensorflow-zephyr-vexriscv-examples.git $NEW_BRANCH
            gh pr create --fill --head $NEW_BRANCH --base bump-zephyr
            gh pr merge --auto --rebase --delete-branch
          else
            echo "no changes";
          fi
